const express = require('express');
const router = express.Router();
const paymentController = require('../controllers/paymentController');
router.post('/create-order', paymentController.createOrder);
router.post('/verify-payment', paymentController.verifyPayment);
router.post('/record-cash', paymentController.recordCashPayment);
router.post('/mark-collected/:paymentId', paymentController.markCashCollected);
router.get('/all', paymentController.getAllPayments);
router.get('/details/:paymentId', paymentController.getPaymentDetails);
module.exports = router;
